services:
  frigate-protect-events:
    build: .
    image: ghcr.io/jasonmadigan/frigate-protect-events:latest
    container_name: frigate-protect-events
    restart: unless-stopped
    network_mode: bridge
    environment:
      - TZ=Europe/Dublin
      - FPE_CONFIG=/app/config/config.yaml
    volumes:
      - /mnt/user/appdata/frigate-protect-events/config.yaml:/app/config/config.yaml:ro
      - /mnt/user/appdata/frigate-protect-events/ssh:/app/ssh:ro
